parameters:

services:
    app.image_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%images_directory%']

    app.albums_normalizer:
            class: AppBundle\Serializer\AlbumsNormalizer

    app.album_normalizer:
            class: AppBundle\Serializer\AlbumNormalizer

    app.image_normalizer:
            class: AppBundle\Serializer\ImageNormalizer
